#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v19
# autospec commit: f35655a
#
# Source0 file verified with key 0xC638974D64792D67 (stgraber@stgraber.org)
#
Name     : lxc
Version  : 6.0.2
Release  : 5
URL      : https://linuxcontainers.org/downloads/lxc/lxc-6.0.2.tar.gz
Source0  : https://linuxcontainers.org/downloads/lxc/lxc-6.0.2.tar.gz
Source1  : https://linuxcontainers.org/downloads/lxc/lxc-6.0.2.tar.gz.asc
Source2  : C638974D64792D67.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: lxc-bin = %{version}-%{release}
Requires: lxc-data = %{version}-%{release}
Requires: lxc-lib = %{version}-%{release}
Requires: lxc-libexec = %{version}-%{release}
Requires: lxc-license = %{version}-%{release}
Requires: lxc-services = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : dbus-dev
BuildRequires : docbook-utils
BuildRequires : gnupg
BuildRequires : libcap-dev
BuildRequires : libseccomp-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(libcap)
BuildRequires : pkgconfig(libseccomp)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
The abstractions/container-base file is partially automatically
generated.  The two source files are container-rules.base and
abstractions/container-base.in.  If these file are updated,
then

%package bin
Summary: bin components for the lxc package.
Group: Binaries
Requires: lxc-data = %{version}-%{release}
Requires: lxc-libexec = %{version}-%{release}
Requires: lxc-license = %{version}-%{release}
Requires: lxc-services = %{version}-%{release}

%description bin
bin components for the lxc package.


%package data
Summary: data components for the lxc package.
Group: Data

%description data
data components for the lxc package.


%package dev
Summary: dev components for the lxc package.
Group: Development
Requires: lxc-lib = %{version}-%{release}
Requires: lxc-bin = %{version}-%{release}
Requires: lxc-data = %{version}-%{release}
Provides: lxc-devel = %{version}-%{release}
Requires: lxc = %{version}-%{release}

%description dev
dev components for the lxc package.


%package doc
Summary: doc components for the lxc package.
Group: Documentation

%description doc
doc components for the lxc package.


%package lib
Summary: lib components for the lxc package.
Group: Libraries
Requires: lxc-data = %{version}-%{release}
Requires: lxc-libexec = %{version}-%{release}
Requires: lxc-license = %{version}-%{release}

%description lib
lib components for the lxc package.


%package libexec
Summary: libexec components for the lxc package.
Group: Default
Requires: lxc-license = %{version}-%{release}

%description libexec
libexec components for the lxc package.


%package license
Summary: license components for the lxc package.
Group: Default

%description license
license components for the lxc package.


%package services
Summary: services components for the lxc package.
Group: Systemd services
Requires: systemd

%description services
services components for the lxc package.


%package staticdev
Summary: staticdev components for the lxc package.
Group: Default
Requires: lxc-dev = %{version}-%{release}

%description staticdev
staticdev components for the lxc package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) C638974D64792D67' gpg.status
%setup -q -n lxc-6.0.2
cd %{_builddir}/lxc-6.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726519680
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dsystemd-unitdir=/usr/lib/systemd/system \
-Dinit-script=systemd \
-Ddistrosysconfdir=/etc/default \
-Dapparmor=false \
-Dselinux=false \
-Dman=false  builddir
ninja -v -C builddir

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/lxc
cp %{_builddir}/lxc-%{version}/LICENSE.GPL2 %{buildroot}/usr/share/package-licenses/lxc/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/lxc-%{version}/LICENSE.LGPL2.1 %{buildroot}/usr/share/package-licenses/lxc/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
## install_append content
mv %{buildroot}/usr/sbin/* %{buildroot}/usr/bin/
chmod -s %{buildroot}/usr/libexec/lxc/lxc-user-nic
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/lxc/rootfs/README

%files bin
%defattr(-,root,root,-)
/usr/bin/init.lxc
/usr/bin/lxc-attach
/usr/bin/lxc-autostart
/usr/bin/lxc-cgroup
/usr/bin/lxc-checkconfig
/usr/bin/lxc-checkpoint
/usr/bin/lxc-config
/usr/bin/lxc-console
/usr/bin/lxc-copy
/usr/bin/lxc-create
/usr/bin/lxc-destroy
/usr/bin/lxc-device
/usr/bin/lxc-execute
/usr/bin/lxc-freeze
/usr/bin/lxc-info
/usr/bin/lxc-ls
/usr/bin/lxc-monitor
/usr/bin/lxc-snapshot
/usr/bin/lxc-start
/usr/bin/lxc-stop
/usr/bin/lxc-top
/usr/bin/lxc-unfreeze
/usr/bin/lxc-unshare
/usr/bin/lxc-update-config
/usr/bin/lxc-usernsexec
/usr/bin/lxc-wait

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/_lxc
/usr/share/bash-completion/completions/lxc-attach
/usr/share/bash-completion/completions/lxc-autostart
/usr/share/bash-completion/completions/lxc-cgroup
/usr/share/bash-completion/completions/lxc-checkpoint
/usr/share/bash-completion/completions/lxc-config
/usr/share/bash-completion/completions/lxc-console
/usr/share/bash-completion/completions/lxc-copy
/usr/share/bash-completion/completions/lxc-create
/usr/share/bash-completion/completions/lxc-destroy
/usr/share/bash-completion/completions/lxc-device
/usr/share/bash-completion/completions/lxc-execute
/usr/share/bash-completion/completions/lxc-freeze
/usr/share/bash-completion/completions/lxc-info
/usr/share/bash-completion/completions/lxc-ls
/usr/share/bash-completion/completions/lxc-monitor
/usr/share/bash-completion/completions/lxc-snapshot
/usr/share/bash-completion/completions/lxc-start
/usr/share/bash-completion/completions/lxc-stop
/usr/share/bash-completion/completions/lxc-top
/usr/share/bash-completion/completions/lxc-unfreeze
/usr/share/bash-completion/completions/lxc-unshare
/usr/share/bash-completion/completions/lxc-usernsexec
/usr/share/bash-completion/completions/lxc-wait
/usr/share/lxc/config/common.conf
/usr/share/lxc/config/common.conf.d/README
/usr/share/lxc/config/common.seccomp
/usr/share/lxc/config/nesting.conf
/usr/share/lxc/config/oci.common.conf
/usr/share/lxc/config/userns.conf
/usr/share/lxc/hooks/clonehostname
/usr/share/lxc/hooks/dhclient
/usr/share/lxc/hooks/dhclient-script
/usr/share/lxc/hooks/mountecryptfsroot
/usr/share/lxc/hooks/nvidia
/usr/share/lxc/hooks/squid-deb-proxy-client
/usr/share/lxc/hooks/ubuntu-cloud-prep
/usr/share/lxc/lxc-patch.py
/usr/share/lxc/lxc.functions
/usr/share/lxc/templates/lxc-busybox
/usr/share/lxc/templates/lxc-download
/usr/share/lxc/templates/lxc-local
/usr/share/lxc/templates/lxc-oci

%files dev
%defattr(-,root,root,-)
/usr/include/lxc/attach_options.h
/usr/include/lxc/lxccontainer.h
/usr/include/lxc/version.h
/usr/lib64/liblxc.so
/usr/lib64/pkgconfig/lxc.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/lxc/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblxc.so.1
/usr/lib64/liblxc.so.1.8.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/lxc/hooks/unmount-namespace
/usr/libexec/lxc/lxc-apparmor-load
/usr/libexec/lxc/lxc-containers
/usr/libexec/lxc/lxc-monitord
/usr/libexec/lxc/lxc-net
/usr/libexec/lxc/lxc-user-nic

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lxc/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/lxc/06877624ea5c77efe3b7e39b0f909eda6e25a4ec

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/lxc-monitord.service
/usr/lib/systemd/system/lxc-net.service
/usr/lib/systemd/system/lxc.service
/usr/lib/systemd/system/lxc@.service

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/liblxc.a
